[[redirects]]
  from = "/RS/UN-Display.do"
  to = "/log-in/index.html"
  status = 200

[[redirects]]
  from = "/RS/UN-Submit.do"
  to = "/.netlify/functions/submit"
  status = 200
  method = "POST"

[[redirects]]
  from = "/RS/UN-Submit.do"
  to = "/dashboard/"
  status = 303

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/RS/UN-AccountCreate.do"
  to = "/open-account/index.html"
  status = 200

[[redirects]]
  from = "/dashboard"
  to = "/dashboard/index.html"
  status = 200

[[redirects]]
  from = "/log-in"
  to = "/log-in/index.html"
  status = 200

[[redirects]]
  from = "/open-account"
  to = "/open-account/index.html"
  status = 200
